-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2022-11-29 18:30:08 GMT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE attendance (
    attendance    DATE NOT NULL,
    enrollment_id INTEGER NOT NULL
);

ALTER TABLE attendance ADD CONSTRAINT attendance_pk PRIMARY KEY ( attendance,
                                                                  enrollment_id );

CREATE TABLE courses (
    title     VARCHAR2(50 CHAR) NOT NULL,
    duration  INTEGER NOT NULL,
    cost      NUMBER(6, 2) NOT NULL,
    course_id INTEGER NOT NULL
);

ALTER TABLE courses ADD constraint courses_cost_ck

check(between(
             300
             AND 2000
      ));

ALTER TABLE courses ADD constraint courses_duration_ck

check(between(
             1
             AND 5
      ));

ALTER TABLE courses ADD CONSTRAINT courses_pk PRIMARY KEY ( course_id );

CREATE TABLE enrollments (
    enrollment_id INTEGER NOT NULL,
    student_id    INTEGER NOT NULL,
    offering_id   INTEGER NOT NULL,
    evaluation    INTEGER
);

ALTER TABLE enrollments
    ADD CONSTRAINT evaluation_check CHECK ( evaluation BETWEEN 0 AND 5 );

ALTER TABLE enrollments ADD CONSTRAINT enrollments_pk PRIMARY KEY ( enrollment_id );

CREATE TABLE examinations (
    pass          CHAR(1) NOT NULL,
    exam_id       INTEGER NOT NULL,
    enrollment_id INTEGER NOT NULL
);

ALTER TABLE examinations ADD CONSTRAINT examinations_pk PRIMARY KEY ( exam_id );

CREATE TABLE instructors (
    name          VARCHAR2(50 CHAR) NOT NULL,
    instructor_id INTEGER NOT NULL
);

ALTER TABLE instructors ADD CONSTRAINT instructors_pk PRIMARY KEY ( instructor_id );

CREATE TABLE offerings (
    start_date    DATE NOT NULL,
    location      VARCHAR2(50 CHAR) NOT NULL,
    offering_id   INTEGER NOT NULL,
    instructor_id INTEGER NOT NULL,
    course_id     INTEGER NOT NULL
);

ALTER TABLE offerings ADD CONSTRAINT offerings_pk PRIMARY KEY ( offering_id );

CREATE TABLE payment_details (
    card_no    VARCHAR2(19 CHAR) NOT NULL,
    student_id INTEGER NOT NULL
);

ALTER TABLE payment_details
    ADD CONSTRAINT verify_card_no CHECK ( REGEXP_LIKE ( card_no,
                                                        '^[[:digit:]]{4} [[:digit:]]{4} [[:digit:]]{4} [[:digit:]]{4}$' ) );

ALTER TABLE payment_details ADD CONSTRAINT payment_details_pk PRIMARY KEY ( card_no,
                                                                            student_id );

CREATE TABLE students (
    student_id   INTEGER NOT NULL,
    name         VARCHAR2(50 CHAR) NOT NULL,
    gender       VARCHAR2(20 CHAR) NOT NULL,
    company_name VARCHAR2(50 CHAR)
);

ALTER TABLE students ADD CONSTRAINT students_pk PRIMARY KEY ( student_id );

ALTER TABLE attendance
    ADD CONSTRAINT attendance_enrollments_fk FOREIGN KEY ( enrollment_id )
        REFERENCES enrollments ( enrollment_id )
            ON DELETE CASCADE;

ALTER TABLE enrollments
    ADD CONSTRAINT enrollments_offerings_fk FOREIGN KEY ( offering_id )
        REFERENCES offerings ( offering_id );

ALTER TABLE enrollments
    ADD CONSTRAINT enrollments_students_fk FOREIGN KEY ( student_id )
        REFERENCES students ( student_id );

ALTER TABLE examinations
    ADD CONSTRAINT examinations_enrollments_fk FOREIGN KEY ( enrollment_id )
        REFERENCES enrollments ( enrollment_id )
            ON DELETE CASCADE;

ALTER TABLE offerings
    ADD CONSTRAINT offerings_courses_fk FOREIGN KEY ( course_id )
        REFERENCES courses ( course_id );

ALTER TABLE offerings
    ADD CONSTRAINT offerings_instructors_fk FOREIGN KEY ( instructor_id )
        REFERENCES instructors ( instructor_id );

ALTER TABLE payment_details
    ADD CONSTRAINT payment_details_students_fk FOREIGN KEY ( student_id )
        REFERENCES students ( student_id )
            ON DELETE CASCADE;



-- Oracle SQL Developer Data Modeler Summary Report:
--
-- CREATE TABLE                             8
-- CREATE INDEX                             0
-- ALTER TABLE                             19
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
--
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
--
-- REDACTION POLICY                         0
--
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
--
-- ERRORS                                   0
-- WARNINGS                                 0
